### ISSUE TITLE
unable to compile on 10.10 with given instructions

### ISSUE THREAD

**Issue by gepatto** [leozimmerman/ofxAudioAnalyzer#1]
I have followed the instructions in the readme and installed all dependencies trough the provided link, added the files to the project and added the needed paths to the project. I am using the 64bit version of openframeworks. However when I try to compile the example projects, I get about 75 linking errors like:

Undefined symbols for architecture x86_64:
  "non-virtual thunk to std::__1::basic_iostream<char, std::__1::char_traits<char> >::~basic_iostream()", referenced from:
      construction vtable for std::__1::basic_iostream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libessentia.a(yamlast.cpp.1.o)

( full output here:   https://gist.github.com/gepatto/208a0b43bb133882cf93  )

**Comment by leozimmerman** [comment]
It seems to be an error with the libraries links. Did you try creating a new project and adding the libraries manually? (libavcodec.a - libavformat.a - libavutil.a - libessentia.a - libfftw3f.a - libsamplerate.a - libswresample.a - libtag.dylib -libyaml.a) Do you have all these files in /usr/local/lib?

**Comment by gepatto** [comment]
Yes I have and yes I do.. 
I am now trying a complete reinstall of Brew (and installed libraries) and see if that helps

**Comment by leozimmerman** [comment]
Try adding the libraries to a 32 bit project. Perhaps, for some reason, you're compiling the libraries in 32 bits, Could it be possible?

**Comment by gepatto** [comment]
I think somehow that might be the case, although I did follow the exact instructions.

I tried reinstalling brew but it made things worse, there are now even more linker errors.
Giving up..  Thanks for your help.

**Comment by tanel** [comment]
Any success solving the issue, @gepatto ? Looks like I have the same show stopper problem at the moment.

**Comment by gepatto** [comment]
No, I gave up. I've upgraded to osx 10.11. 
Maybe I'll try again once OF0.90 is final.

**Comment by tanel** [comment]
I gave up too. Now using https://github.com/borg/ofxGist and https://github.com/darrenmothersele/ofxBeat

**Comment by leozimmerman** [comment]
Updating the addon to OF 0.9.0 I found this error. The problem was an icompatibility of the C++ Standard Library used to compile Essentia and OF. (libc++ / libstdc++).
Now,OF 0.9.0 and the last version of Essentia use both libc++, so there should be no problem.

**Comment by karlhugle** [comment]
it works fine after updating. while today I update to 10.11.3 (15D21), errors show again....

**Comment by leozimmerman** [comment]
I didn't update my system to 10.11 yet so I can't try to find the error in this osx version. But if the errors you get are the same than before (std library related erros) try recompiling Essentia and make sure that both OF and Essentia are compiling with the same C++ Standard Library

**Comment by leozimmerman** [comment]
New update has been tested with OSX 10.11.6. Now static builds of libraries are included in the repository making much easier to compile the addon.
