### ISSUE TITLE
Error include <MobileCoreServices/MobileCoreServices.h on audiodecodercoreaudio.h file.

### ISSUE THREAD

**Issue by ImanolGo** [leozimmerman/ofxAudioAnalyzer#10]
While compiling the under MacOS Sierra, it complains that 

"include <MobileCoreServices/MobileCoreServices.h on audiodecodercoreaudio.h file." not found.

I solved it by using
#ifdef TARGET_OF_IOS

instead of
#ifdef TARGET_OF_IPHONE

**Comment by dimitre** [comment]
+1
