### ISSUE TITLE
MULTI_PITCHES algorithm results to zero size vector

### ISSUE THREAD

**Issue by stc** [leozimmerman/ofxAudioAnalyzer#12]
trying to get multi pitch detection (using the ofxAAMultiPitchKlapuriAlgorithm)
however, the resulting vector size is always zero. can't track down what I miss there

**Comment by leozimmerman** [comment]
The multi pitch detection functionality is not implemented properly yet. I've made some tests but didn't get decent results with the Essentia multipitch algorithms.
