### ISSUE TITLE
need of ofBaseSoundPlayer.h to make it work in OF 0.10

### ISSUE THREAD

**Issue by Dazzid** [leozimmerman/ofxAudioAnalyzer#13]
Hello,
I would like to implement your library in a research project made in OF 0.10. To implement ofBaseSoundPlayer.h, just coping it into the new sound library in OF would be enough to make it work?
Any suggestion?
Best

**Comment by leozimmerman** [comment]
I haven't tested this addon with OF 0.10 yet. I'l try to do it asap to make it compatible and I'll let you know.
Thanks for the advice.

**Comment by leozimmerman** [comment]
I've updated ofSoundPlayerExtended and ofxAudioAnalyzer examples to work with OF 0.10.0. Check version 1.1
