### ISSUE TITLE
Examples crashing on runtime

### ISSUE THREAD

**Issue by wanbinkimoon** [leozimmerman/ofxAudioAnalyzer#15]
I'm getting this error on every example, any idea why?
`Thread 1: EXC_ARITHMETIC (code=EXC_I386_DIV, subcode=0x0)`
![screenshot 2018-11-15 at 19 21 30](https://user-images.githubusercontent.com/10087639/48573151-acee2380-e90b-11e8-98ec-114eb5b075ed.png)

**Comment by wanbinkimoon** [comment]
Apparently the error is due to of 10.0.0 upgrading to version 10.0.1 automagically fix the memory leak

**Comment by leozimmerman** [comment]
Yes, recently they merged Pull Request I created: https://github.com/openframeworks/openFrameworks/commit/9945514af5cdacd22f333f6abfb4f760ccc2ea58#diff-ea043752be73b0b92f70a947d74cbaae 

Can you please check if this crash is because of this bug?

**Comment by wanbinkimoon** [comment]
Yup he was the guy!
