### ISSUE TITLE
Libraries missing while running on other machine

### ISSUE THREAD

**Issue by jivido** [leozimmerman/ofxAudioAnalyzer#3]
Hi,

I have a problem with the linking of the depending libraries (I think).
When I follow the instructions from the Readme I can succesfully build and run my project. But when I try to run my app on another machine it doesn't start and gives an error, saying:
Dyld Error Message: Library not loaded: /usr/local/opt/taglib/lib/libtag.1.dylib
Reason: image not found
All the libraries, mentioned in the Readme, are under 'Link Binary With Libraries' in the Build Phases. 
I'm quite new to the linking of libraries, so I'm not sure what to do. 

Thanks :)

**Comment by leozimmerman** [comment]
Try installing the Essentia libraries and its dependencies in the computer where you're trying to run the app

**Comment by jivido** [comment]
I think it's a bit inconvenient to have to install the library each time (I'm running it on multiple machines), but it solves the problem for now, thanks!

**Comment by jivido** [comment]
I have trouble running the app on machines with ffmpeg 3.0 installed (recently updated), could it be possible that this problem is caused because I was using ffmpeg 2.8.4 while linking and building the project? When I update my ffmpeg to 3.0 I get an error in XCode: 
_dyld: Library not loaded: /usr/local/opt/ffmpeg/lib/libavformat.56.dylib
  Referenced from: /usr/local/opt/essentia/lib/libessentia.dylib
  Reason: image not found_
I find a libavformat.57.dylib file in my usr/local/lib, so I think (up-to-date) essentia is still linking to the (older?) 56 file. 
Another thing that might cause a problem (I read it in an error-report when trying to open the app (with ffmpeg 2.8.4, but different machine))
_Dyld Error Message:
  Library not loaded: /usr/local/opt/libvo-aacenc/lib/libvo-aacenc.0.dylib
  Referenced from: /usr/local/opt/ffmpeg/lib/libavutil.54.dylib
  Reason: image not found_
https://ffmpeg.org/index.html#removing_external_aac_encoders
I'm not sure where to find the problem...

**Comment by jivido** [comment]
Unlinking ffmpeg solved the problem :) using:
_brew install essentia --HEAD --without-ffmpeg_
