### ISSUE TITLE
New examples request

### ISSUE THREAD

**Issue by transat** [leozimmerman/ofxAudioAnalyzer#4]
Thanks for your work. Any chance to include examples to illustrate some of the other essentia algorithms such as chord detection or beat detection?

**Comment by leozimmerman** [comment]
I have plans of adding more examples, algorithms, and documentation soon.

**Comment by transat** [comment]
Fantastic. Looking forward to it. Cheers.

**Comment by transat** [comment]
It would be great if the examples could use ofParameters, by the way!

**Comment by leozimmerman** [comment]
I've finally finished the update. Check the new examples, and added features.
