### ISSUE TITLE
Error while linking to essentia

### ISSUE THREAD

**Issue by TradDog** [leozimmerman/ofxAudioAnalyzer#5]
Hi, 
Trying to compile on UbuntuStudio 16.04 with standard Linux tools.
I get errors while linking. I suspect a wrongly define compiler macro but not sure how to correct it
if it is indeed the case. I have also compiled and installed essentia in case there was an issue with the static library shipped. 

Thanks for the help. 

Trad

Compiling example-allAlgorithms for Release
make[1]: Entering directory '/home/traddog/Desktop/of_v0.9.3_linux64_release/addons/ofxAudioAnalyzer/example-allAlgorithms'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
Linking bin/example-allAlgorithms for linux64
g++ -o bin/example-allAlgorithms  obj/linux64/Release/src/ofApp.o obj/linux64/Release/src/main.o /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/obj/linux64/Release/ofxAudioAnalyzer/src/ofxAAMultiPitchKlapuriAlgorithm.o /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/obj/linux64/Release/ofxAudioAnalyzer/src/ofSoundPlayerExtended.o /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/obj/linux64/Release/ofxAudioAnalyzer/src/ofxAudioAnalyzerAlgorithms.o /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/obj/linux64/Release/ofxAudioAnalyzer/src/ofxAudioAnalyzerUnit.o /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/obj/linux64/Release/ofxAudioAnalyzer/src/ofxAudioAnalyzer.o /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/obj/linux64/Release/ofxAudioAnalyzer/src/ofxAAOnsetsAlgorithm.o /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/obj/linux64/Release/ofxGui/src/ofxSliderGroup.o /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/obj/linux64/Release/ofxGui/src/ofxLabel.o /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/obj/linux64/Release/ofxGui/src/ofxBaseGui.o /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/obj/linux64/Release/ofxGui/src/ofxGuiGroup.o /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/obj/linux64/Release/ofxGui/src/ofxToggle.o /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/obj/linux64/Release/ofxGui/src/ofxSlider.o /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/obj/linux64/Release/ofxGui/src/ofxPanel.o /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/obj/linux64/Release/ofxGui/src/ofxButton.o /home/traddog/Desktop/of_v0.9.3_linux64_release/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a  /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/ofxAudioAnalyzer/libs/essentia/lib/linux64/libessentia.a /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/ofxAudioAnalyzer/libs/fftw3f/lib/linux64/libfftw3f.a /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/ofxAudioAnalyzer/libs/essentia/lib/linux64/libessentia.a /home/traddog/Desktop/of_v0.9.3_linux64_release/addons/ofxAudioAnalyzer/libs/fftw3f/lib/linux64/libfftw3f.a -Wl,-rpath=./libs:./bin/libs -Wl,--as-needed -Wl,--gc-sections -Wl,-rpath=./libs -L/home/traddog/Desktop/of_v0.9.3_linux64_release/libs/fmodex/lib/linux64/ -lfmodex /home/traddog/Desktop/of_v0.9.3_linux64_release/libs/glfw/lib/linux64/libglfw3.a /home/traddog/Desktop/of_v0.9.3_linux64_release/libs/kiss/lib/linux64/libkiss.a /home/traddog/Desktop/of_v0.9.3_linux64_release/libs/tess2/lib/linux64/libtess2.a  /home/traddog/Desktop/of_v0.9.3_linux64_release/libs/poco/lib/linux64/libPocoNetSSL.a /home/traddog/Desktop/of_v0.9.3_linux64_release/libs/poco/lib/linux64/libPocoNet.a /home/traddog/Desktop/of_v0.9.3_linux64_release/libs/poco/lib/linux64/libPocoCrypto.a /home/traddog/Desktop/of_v0.9.3_linux64_release/libs/poco/lib/linux64/libPocoUtil.a /home/traddog/Desktop/of_v0.9.3_linux64_release/libs/poco/lib/linux64/libPocoJSON.a /home/traddog/Desktop/of_v0.9.3_linux64_release/libs/poco/lib/linux64/libPocoXML.a /home/traddog/Desktop/of_v0.9.3_linux64_release/libs/poco/lib/linux64/libPocoFoundation.a  -lz -lgstapp-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -ludev -lfontconfig -lfreetype -lsndfile -lopenal -lssl -lcrypto -lpulse-simple -lpulse -lasound -lGLEW -lGLU -lGL -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lmpg123 -lglut -lX11 -lXrandr -lXxf86vm -lXi -lXcursor -ldl -lpthread -lfreeimage -lrtaudio -lboost_filesystem -lboost_system
/home/traddog/Desktop/of_v0.9.3_linux64_release/addons/obj/linux64/Release/ofxAudioAnalyzer/src/ofxAudioAnalyzerUnit.o: In function `ofxAudioAnalyzerUnit::setup(int, int)':
ofxAudioAnalyzerUnit.cpp:(.text+0x4f22): undefined reference to`essentia::standard::Algorithm::input(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
ofxAudioAnalyzerUnit.cpp:(.text+0x4f6f): undefined reference to `essentia::standard::Algorithm::output(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
ofxAudioAnalyzerUnit.cpp:(.text+0x4fa8): undefined reference to`essentia::standard::Algorithm::input(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
o

**Comment by leozimmerman** [comment]
The compilation is not linking libessentia.a . Dont know if its a directory linking issue, or is there any compatibility issue with the static version included and your system. Thos std relate errors maybe caused by a difference in c++ versions used to compile OF and the library (c++11). Thats the entire output of the make command? please try a make clean, and post the entire output of the make build. Also check if you're compiling OF using c++11

**Comment by wezside** [comment]
I had the same issue on Ubuntu 16.04. For me to get this to work I had to recompile openFrameworks with the following added to the make file. Maybe there is an easier way to do this per project?

`openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/config.linux.common.mk` 

``` 
ifeq ($(CXX),g++-5)
    PLATFORM_CFLAGS = -Wall -std=c++14 -DGCC_HAS_REGEX -D_GLIBCXX_USE_CXX11_ABI=1
else
    ifeq ($(CXX),g++-4.9)
        PLATFORM_CFLAGS = -Wall -std=c++14 -DGCC_HAS_REGEX -D_GLIBCXX_USE_CXX11_ABI=1
    else
        ifeq ($(CXX),g++-4.8)
            PLATFORM_CFLAGS = -Wall -std=c++11
        else
            PLATFORM_CFLAGS = -Wall -std=c++11
        endif
    endif
endif
```

More on this and the GCC 5 changes here: http://stackoverflow.com/questions/33394934/converting-std-cxx11string-to-stdstring

**Comment by TradDog** [comment]
Thanks for the info. I´ll give it another try.

**Comment by fsguiglia** [comment]
Hi, I also had this issue on Ubuntu 16.04, solved it by recompiling Essentia following [essentia_compilation.md](https://github.com/leozimmerman/ofxAudioAnalyzer/blob/master/essentia_compilation.md).
