### ISSUE TITLE
Examples not building on OSX 10.12,  OF 9.4

### ISSUE THREAD

**Issue by greena1re** [leozimmerman/ofxAudioAnalyzer#6]
Problem is with ofxAudioDecoder, which can't seem to find `<audioencoder.h>` 

any ideas how to fix? 

<img width="887" alt="screenshot 2016-10-15 14 14 18" src="https://cloud.githubusercontent.com/assets/2187239/19413435/b24580e4-92e1-11e6-9a7a-1a14407e6e63.png">

**Comment by leozimmerman** [comment]
Are you using this fork of ofxAudioDecoder: https://github.com/leozimmerman/ofxAudioDecoder ?? Have you check this: https://github.com/leozimmerman/ofxAudioAnalyzer#audio-file-player ??

**Comment by greena1re** [comment]
No I'm sorry I was using the main branch not your fork !

worked once I used your fork.
