### ISSUE TITLE
Assistance with min max values for GUI sliders

### ISSUE THREAD

**Issue by transat** [leozimmerman/ofxAudioAnalyzer#9]
Hi @leozimmerman I'm getting back into openFrameworks after a few months off and really liking what you've done with ofxAudioAnalyzer. I've changed it to use ofParameter<float> and have set it up to work with ofxGuiExtended. But I'm not sure what the min and max values should be for all the float sliders. Any chance you could assist with this? Cheers.

**Comment by transat** [comment]
Ah. I've just realised I should be using the normalised values for sliders. In the ofxGuiExtended sliders would be set up like this in my case: `anAlgorithm.set("Algorithm Name", 0.0, 0.0, 1.0);` Cheers!

**Comment by leozimmerman** [comment]
Exactly min and max values are for normalizing, you can choose whether to use the raw value or normalized (some algorithms output normalized values for default).
I've seen your pull request for 0.9.8, thanks for taking the time to work on this addon. I haven't work with OF 0.9.8 yet, but I'll take a look at it and try. I need to find a way to organize OF version compatibility first, I was thiniking in adding tags or a Changelog file.
